export const FURNITURE_CATALOG = {
  baner:              { file: '01_baner.png',              w: 40,  h: 60,  sittable: false, price: 20 , solid: false },
  bar_counter1:       { file: '02_bar_counter1.png',       w: 160, h: 70,  sittable: false, price: 120, solid: true },
  bar_counter2:       { file: '03_bar_counter2 .png',      w: 160, h: 70,  sittable: false, price: 120, solid: true },
  barrel:             { file: '04_barrel.png',             w: 35,  h: 45,  sittable: false, price: 15, solid: true },
  cupboard:           { file: '05_cupboard.png',           w: 70,  h: 90,  sittable: false, price: 80, solid: true },
  bookcase_small:     { file: '06_bookcase_small.png',     w: 70,  h: 90,  sittable: false, price: 60, solid: true },
  cabinet:            { file: '07_cabinet.png',            w: 70,  h: 80,  sittable: false, price: 70, solid: true },
  candle:             { file: '08_candle.png',             w: 25,  h: 30,  sittable: false, price: 10, solid: true },
  chair:              { file: '09_chair.png',              w: 30,  h: 60,  sittable: true,  seatDx: 0, seatDy: 10, price: 25, solid: true},
  chair2:             { file: '10_chair.png',              w: 40,  h: 45,  sittable: true,  seatDx: 0, seatDy: 10, price: 25, solid: true },
  chair_blue:         { file: '11_chair_blue.png',         w: 45,  h: 50,  sittable: true,  seatDx: 0, seatDy: 10, price: 30, solid: true },
  chair_red:          { file: '12_chair_red.png',          w: 40,  h: 45,  sittable: true,  seatDx: 0, seatDy: 10, price: 30, solid: true},
  crate:              { file: '13_crate.png',              w: 40,  h: 40,  sittable: false, price: 12, solid: true },
  dresser:            { file: '14_dresser.png',            w: 70,  h: 60,  sittable: false, price: 65, solid: true },
  fireplace:          { file: 'fireplace(off).png',          nightFile : 'fireplace(night).png', w: 100, h: 80,  sittable: false, price: 150, solid: true},
  long_table:         { file: '17_long_table.png',         w: 120, h: 60,  sittable: false, price: 80, solid: true },
  nightstand:         { file: '18_nightstand.png',         w: 45,  h: 50,  sittable: false, price: 35, solid: true },
  painting:           { file: '19_painting.png',           w: 50,  h: 40,  sittable: false, price: 40, solid: false },
  plant_big:          { file: '20_plant_big.png',          w: 40,  h: 50,  sittable: false, price: 25, solid: true },
  plant_blue:         { file: '21_plant_blue.png',         w: 35,  h: 45,  sittable: false, price: 20, solid: true },
  plant_small:        { file: '22_plant_small.png',        w: 30,  h: 40,  sittable: false, price: 15, solid: true },
  red_carpet:         { file: '23_red_carpet .png',        w: 120, h: 70,  sittable: false, price: 55, solid: false },
  sofa_blue:          { file: '24_sofa_blue.png',          w: 110, h: 60,  sittable: true,  seatDx: 0, seatDy: 15, price: 90, solid: true},
  sofa_red:           { file: '25_sofa_red.png',           w: 110, h: 60,  sittable: true,  seatDx: 0, seatDy: 15, price: 90, solid: true},
  table_long:         { file: '26_table_long.png',         w: 130, h: 90,  sittable: false, price: 85, solid: true },
  table_round:        { file: '27_table_round.png',        w: 90,  h: 90,  sittable: false, price: 70, solid: true },
  table_square:       { file: '28_table_square.png',       w: 80,  h: 80,  sittable: false, price: 60, solid: true },
  table_square_plant: { file: '29_table_square_plant.png', w: 80,  h: 80,  sittable: false, price: 75, solid: true  },
  wardrobe:           { file: '30_wardrobe.png',           w: 60,  h: 80,  sittable: false, price: 85, solid: true },
};

export const FURNITURE_SIZES = Object.fromEntries(
  Object.entries(FURNITURE_CATALOG).map(([k, v]) => [k, { w: v.w, h: v.h }])
);