export const FURNITURE_CATALOG = {
  baner:              { file: '01_baner.png',              w: 40,  h: 60,  sittable: false, price: 20  },
  bar_counter1:       { file: '02_bar_counter1.png',       w: 160, h: 70,  sittable: false, price: 120 },
  bar_counter2:       { file: '03_bar_counter2 .png',      w: 160, h: 70,  sittable: false, price: 120 },
  barrel:             { file: '04_barrel.png',             w: 35,  h: 45,  sittable: false, price: 15  },
  cupboard:           { file: '05_cupboard.png',           w: 70,  h: 90,  sittable: false, price: 80  },
  bookcase_small:     { file: '06_bookcase_small.png',     w: 70,  h: 90,  sittable: false, price: 60  },
  cabinet:            { file: '07_cabinet.png',            w: 70,  h: 80,  sittable: false, price: 70  },
  candle:             { file: '08_candle.png',             w: 25,  h: 30,  sittable: false, price: 10  },
  chair:              { file: '09_chair.png',              w: 30,  h: 60,  sittable: true,  seatDx: 0, seatDy: 10, price: 25 },
  chair2:             { file: '10_chair.png',              w: 40,  h: 45,  sittable: true,  seatDx: 0, seatDy: 10, price: 25 },
  chair_blue:         { file: '11_chair_blue.png',         w: 45,  h: 50,  sittable: true,  seatDx: 0, seatDy: 10, price: 30 },
  chair_red:          { file: '12_chair_red.png',          w: 40,  h: 45,  sittable: true,  seatDx: 0, seatDy: 10, price: 30 },
  crate:              { file: '13_crate.png',              w: 40,  h: 40,  sittable: false, price: 12  },
  dresser:            { file: '14_dresser.png',            w: 70,  h: 60,  sittable: false, price: 65  },
  fireplace:          { file: '15_fireplace.png',          w: 100, h: 80,  sittable: false, price: 150 },
  lantern:            { file: '16_lantern.png',            nightFile: '16_lantern_on.png', w: 30, h: 40, sittable: false, price: 20 },
  long_table:         { file: '17_long_table.png',         w: 120, h: 60,  sittable: false, price: 80  },
  nightstand:         { file: '18_nightstand.png',         w: 45,  h: 50,  sittable: false, price: 35  },
  painting:           { file: '19_painting.png',           w: 50,  h: 40,  sittable: false, price: 40  },
  plant_big:          { file: '20_plant_big.png',          w: 40,  h: 50,  sittable: false, price: 25  },
  plant_blue:         { file: '21_plant_blue.png',         w: 35,  h: 45,  sittable: false, price: 20  },
  plant_small:        { file: '22_plant_small.png',        w: 30,  h: 40,  sittable: false, price: 15  },
  red_carpet:         { file: '23_red_carpet .png',        w: 120, h: 70,  sittable: false, price: 55  },
  sofa_blue:          { file: '24_sofa_blue.png',          w: 110, h: 60,  sittable: true,  seatDx: 0, seatDy: 15, price: 90 },
  sofa_red:           { file: '25_sofa_red.png',           w: 110, h: 60,  sittable: true,  seatDx: 0, seatDy: 15, price: 90 },
  table_long:         { file: '26_table_long.png',         w: 130, h: 90,  sittable: false, price: 85  },
  table_round:        { file: '27_table_round.png',        w: 90,  h: 90,  sittable: false, price: 70  },
  table_square:       { file: '28_table_square.png',       w: 80,  h: 80,  sittable: false, price: 60  },
  table_square_plant: { file: '29_table_square_plant.png', w: 80,  h: 80,  sittable: false, price: 75  },
  wardrobe:           { file: '30_wardrobe.png',           w: 60,  h: 80,  sittable: false, price: 85  },
};

export const FURNITURE_SIZES = Object.fromEntries(
  Object.entries(FURNITURE_CATALOG).map(([k, v]) => [k, { w: v.w, h: v.h }])
);