import { INITIAL_FURNITURE } from './constants';

export const initialState = {
  phase: 'menu',
  lastSession: null,
  lastSessionDate: null,
  coins: 0,
  reputation: 0,
  cafe: {
    name: 'Lunaria Cafe',
    currentCustomers: 0,
    maxCustomers: 8,
    timeOfDay: 'day',
    bgMode: 'immersive', // 'immersive' | 'reallife' | 'freestyle'
    decorateMode: false,
    decorateTool: 'place',
    placeFurnitureType: 'plant_big',
    placeFurnitureRotation: 0,
    pendingFurniture: null,
    furniture: INITIAL_FURNITURE,
  },
  focus: {
    status: 'idle',
    elapsed: 0,
    duration: 25 * 60,
    mode: 'pomodoro',
  },
  attention: {
    score: 85,
    chaosLevel: 0,
    phoneDetected: false,
    userPresent: true,
    chaosEvents: [],
    warningMessage: '',
    source: 'offline',
    phoneWarningStart: null,
    phoneFreeSince: null,
    gazeFocusedSince: null,
  },
  journal: {
    noteHeader: '',
    note: '',
    todoHeader: '',
    todos: [],
  },
  npcs: {
    customers: [],
    rabbits: [
      { id: 'rabbit-1', x: 200, y: 350, mood: 'happy' },
      { id: 'rabbit-2', x: 500, y: 400, mood: 'sleepy' },
    ],
    major: [
      { id: 'npc-1', name: 'Mira', emoji: '🦊', role: 'Regular', personality: 'Cheerful and curious', schedule: 'Every evening', favoriteOrder: 'Moon Latte'    },
      { id: 'npc-2', name: 'Theo', emoji: '🧙', role: 'Scholar', personality: 'Quiet and studious',   schedule: 'Late nights',   favoriteOrder: 'Dark Brew'     },
      { id: 'npc-3', name: 'Luna', emoji: '🌙', role: 'Dreamer', personality: 'Whimsical and soft',   schedule: 'Weekends',      favoriteOrder: 'Starberry Tea' },
    ],
  },
  audio: {
    masterVolume: 0.8,
    musicVolume: 0.6,
    ambienceVolume: 0.5,
    sfxVolume: 0.7,
    rainEnabled: true,
    fireplaceEnabled: false,
    chatterEnabled: true,
  },
  stats: {
    totalSessions: 0,
    totalFocusSeconds: 0,
    totalMinutes: 0,
    bestStreak: 0,
    totalFocusMinutes: 0,
    coinsEarned: 0,
    customersTotal: 0,
    currentStreak: 0,
    chaosEvents: 0,
    todayMinutes: 0,
    todaySeconds: 0,
    todayDate: null,
    dailyGoal: 60,
    weeklyData: [0, 0, 0, 0, 0, 0, 0],
    weekStartDate: null,
  },
  ui: {
    popups: [],
    coinFloat: null,
  },
};
